### ISSUE TITLE
Important and very real issue that will garner much heated discussion

### ISSUE THREAD

**Issue by christoomey** [christoomey/vim-right-motion#7]

**Comment by christoomey** [comment]
I have strong feelings and opinions about the architecture of this feature. Have we fully considered all options, especially using Kubernetes?

**Comment by MattMSumner** [comment]
I disagree with your strong feelings are present here some of my own. What about using docker-compose to manage everything in the cloud and don't have a local environment at all?

**Comment by christoomey** [comment]
![image](https://cloud.githubusercontent.com/assets/420113/21064084/008d60a8-be27-11e6-8da0-6b90f9e5be33.png)

**Comment by christoomey** [comment]
![image](https://cloud.githubusercontent.com/assets/420113/21064094/10c2a78a-be27-11e6-8fb9-4c40bdd7a453.png)

**Comment by MattMSumner** [comment]
![giphy-14](https://cloud.githubusercontent.com/assets/759721/21064104/17b77f48-be27-11e6-9710-1c663a61bd8c.gif)

**Comment by MattMSumner** [comment]
![red-approved-stamp-clip-art-at-clker-com-vector-clip-art-online-ttmimt-clipart](https://cloud.githubusercontent.com/assets/759721/21064124/32f0431c-be27-11e6-9ac9-f479b5e782b1.png)

**Comment by christoomey** [comment]
Cancel that, more discussion needed!!!

**Comment by MattMSumner** [comment]
![giphy-6](https://cloud.githubusercontent.com/assets/759721/21064142/4b3110c8-be27-11e6-98e4-3aacee5337de.gif)

**Comment by MattMSumner** [comment]
![giphy-3](https://cloud.githubusercontent.com/assets/759721/21064170/6d20f4fa-be27-11e6-9883-547ad0da3b02.gif)
